import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export function generatePOPdf(po) {
  const doc = new jsPDF();
  const sym = { USD: '$', EUR: '€', INR: '₹', GBP: '£', AUD: 'A$' }[po.currency] || po.currency;
  const fmt = (v) => `${sym}${(v || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('PURCHASE ORDER', 14, 22);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(`PO Number: ${po.orderNumber}`, 14, 32);
  doc.text(`Date: ${new Date(po.orderDate).toLocaleDateString()}`, 14, 38);
  doc.text(`Status: ${(po.status || '').toUpperCase()}`, 14, 44);

  // Supplier info — right side
  doc.setTextColor(0);
  doc.setFont('helvetica', 'bold');
  doc.text('Supplier', 130, 32);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(po.supplier || '', 130, 38);
  if (po.deliveryAddress) {
    const addrLines = doc.splitTextToSize(po.deliveryAddress, 65);
    doc.text(addrLines, 130, 44);
  }

  // PO Details
  doc.setFontSize(9);
  doc.setTextColor(80);
  let y = 56;
  if (po.paymentTerms) { doc.text(`Payment Terms: ${po.paymentTerms}`, 14, y); y += 5; }
  if (po.expectedDeliveryDate) { doc.text(`Expected Delivery: ${new Date(po.expectedDeliveryDate).toLocaleDateString()}`, 14, y); y += 5; }
  if (po.approverName) { doc.text(`Approver: ${po.approverName}`, 14, y); y += 5; }
  if (po.createdByName) { doc.text(`Created By: ${po.createdByName}`, 14, y); y += 5; }

  // Line separator
  y += 3;
  doc.setDrawColor(200);
  doc.line(14, y, 196, y);
  y += 8;

  // Items table
  const tableData = (po.items || []).map((item, idx) => [
    idx + 1,
    item.name || '',
    item.description || '',
    item.qty || 0,
    fmt(item.rate),
    `${item.tax || 0}%`,
    fmt(item.amount),
  ]);

  doc.autoTable({
    startY: y,
    head: [['#', 'Item', 'Description', 'Qty', 'Rate', 'Tax', 'Amount']],
    body: tableData,
    theme: 'striped',
    headStyles: { fillColor: [79, 70, 229], fontSize: 9 },
    styles: { fontSize: 8, cellPadding: 3 },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 40 },
      2: { cellWidth: 45 },
      3: { cellWidth: 18, halign: 'right' },
      4: { cellWidth: 25, halign: 'right' },
      5: { cellWidth: 18, halign: 'right' },
      6: { cellWidth: 28, halign: 'right' },
    },
  });

  // Summary
  const finalY = doc.lastAutoTable.finalY + 10;
  const summaryX = 130;
  doc.setFontSize(9);
  doc.setTextColor(80);

  let sY = finalY;
  doc.text('Subtotal:', summaryX, sY);
  doc.text(fmt(po.subtotal), 190, sY, { align: 'right' }); sY += 6;
  doc.text('Tax:', summaryX, sY);
  doc.text(fmt(po.taxTotal), 190, sY, { align: 'right' }); sY += 6;
  if (po.shipping) { doc.text('Shipping:', summaryX, sY); doc.text(fmt(po.shipping), 190, sY, { align: 'right' }); sY += 6; }
  if (po.discount) { doc.text('Discount:', summaryX, sY); doc.text(`-${fmt(po.discount)}`, 190, sY, { align: 'right' }); sY += 6; }

  doc.setDrawColor(200);
  doc.line(summaryX, sY, 190, sY);
  sY += 6;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0);
  doc.text('Total:', summaryX, sY);
  doc.text(`${po.currency} ${fmt(po.total)}`, 190, sY, { align: 'right' });

  // Notes
  if (po.notes) {
    sY += 14;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('Terms & Notes:', 14, sY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80);
    const noteLines = doc.splitTextToSize(po.notes, 175);
    doc.text(noteLines, 14, sY + 5);
  }

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(7);
  doc.setTextColor(150);
  doc.text('Generated by OrderBook', 14, pageHeight - 10);
  doc.text(`Generated on ${new Date().toLocaleString()}`, 190, pageHeight - 10, { align: 'right' });

  return doc;
}
